version: '2'
services:
    npm:
        image: node:6
        env_file: .env
        entrypoint: bash
        # command: run start:dev
        ports:
            - "$PORT:$PORT"
        working_dir: /app
        links:
            - redis
        volumes:
            - .:/app
    redis:
        image: redis:3
        ports:
          - "6379:6379"
